/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      user_name: "Alex Ross",
      first_name: "Alex",
      last_name: "Ross",
      email: "awhr95@@gmail.com",
      password: "",
      bio: "I am Alex and I live in Clapham. I would love to offer up my time to support a good cause!",
      current_number_of_opportunities: 2,
      total_opportunities: 6,
    },
    {
      id: 2,
      user_name: "Sorcha O'Sullivan",
      first_name: "Sorcha",
      last_name: "O'Sullivan",
      email: "sorcha@gmail.com",
      password: "",
      bio: "I am Sorcha and I live in Balham. I would love to offer up my time to support a good cause!",
      current_number_of_opportunities: 1,
      total_opportunities: 19,
    },
    {
      id: 3,
      user_name: "John Doe",
      first_name: "John",
      last_name: "Doe",
      email: "john.doe@gmail.com",
      password: "",
      bio: "I'm John and I'm passionate about making a positive impact in the community.",
      current_number_of_opportunities: 3,
      total_opportunities: 10,
    },
    {
      id: 4,
      user_name: "Emily Johnson",
      first_name: "Emily",
      last_name: "Johnson",
      email: "emily.johnson@gmail.com",
      password: "",
      bio: "Hi, I'm Emily. I reside in Wimbledon and eager to contribute to meaningful causes.",
      current_number_of_opportunities: 0,
      total_opportunities: 8,
    },
    {
      id: 5,
      user_name: "Daniel Smith",
      first_name: "Daniel",
      last_name: "Smith",
      email: "daniel.smith@gmail.com",
      password: "",
      bio: "Daniel here! Living in Richmond and ready to volunteer my time for a better world.",
      current_number_of_opportunities: 2,
      total_opportunities: 15,
    },
    {
      id: 6,
      user_name: "Aisha Patel",
      first_name: "Aisha",
      last_name: "Patel",
      email: "aisha.patel@gmail.com",
      password: "",
      bio: "Aisha from Hammersmith, excited to contribute to community welfare projects.",
      current_number_of_opportunities: 1,
      total_opportunities: 5,
    },
    {
      id: 7,
      user_name: "Chris Turner",
      first_name: "Chris",
      last_name: "Turner",
      email: "chris.turner@gmail.com",
      password: "",
      bio: "Chris, residing in Fulham, looking forward to making a positive difference.",
      current_number_of_opportunities: 4,
      total_opportunities: 12,
    },
    {
      id: 8,
      user_name: "Sophie Brown",
      first_name: "Sophie",
      last_name: "Brown",
      email: "sophie.brown@gmail.com",
      password: "",
      bio: "Sophie, a Battersea resident, committed to volunteering for community development.",
      current_number_of_opportunities: 0,
      total_opportunities: 7,
    },
    {
      id: 9,
      user_name: "Michael Adams",
      first_name: "Michael",
      last_name: "Adams",
      email: "michael.adams@gmail.com",
      password: "",
      bio: "Michael, a Clapham local, eager to give back to the community through volunteering.",
      current_number_of_opportunities: 2,
      total_opportunities: 9,
    },
    {
      id: 10,
      user_name: "Elena Rodriguez",
      first_name: "Elena",
      last_name: "Rodriguez",
      email: "elena.rodriguez@gmail.com",
      password: "",
      bio: "Elena, residing in Putney, passionate about contributing to social causes.",
      current_number_of_opportunities: 1,
      total_opportunities: 14,
    },
    {
      id: 11,
      user_name: "Omar Khan",
      first_name: "Omar",
      last_name: "Khan",
      email: "omar.khan@gmail.com",
      password: "",
      bio: "Omar here! Living in Tooting and excited to make a positive impact in the community.",
      current_number_of_opportunities: 3,
      total_opportunities: 11,
    },
    {
      id: 12,
      user_name: "Isabella White",
      first_name: "Isabella",
      last_name: "White",
      email: "isabella.white@gmail.com",
      password: "",
      bio: "Isabella, a resident of Chelsea, ready to dedicate time for community service.",
      current_number_of_opportunities: 0,
      total_opportunities: 6,
    },
    {
      id: 13,
      user_name: "Samuel Taylor",
      first_name: "Samuel",
      last_name: "Taylor",
      email: "samuel.taylor@gmail.com",
      password: "",
      bio: "Samuel, living in Kingston, enthusiastic about contributing to charitable causes.",
      current_number_of_opportunities: 2,
      total_opportunities: 13,
    },
    {
      id: 14,
      user_name: "Mia Wilson",
      first_name: "Mia",
      last_name: "Wilson",
      email: "mia.wilson@gmail.com",
      password: "",
      bio: "Mia, a Wandsworth resident, passionate about volunteering for a better community.",
      current_number_of_opportunities: 1,
      total_opportunities: 8,
    },
    {
      id: 15,
      user_name: "Liam Murphy",
      first_name: "Liam",
      last_name: "Murphy",
      email: "liam.murphy@gmail.com",
      password: "",
      bio: "Liam, a Brixton local, ready to contribute time and effort to support community initiatives.",
      current_number_of_opportunities: 4,
      total_opportunities: 17,
    },
    {
      id: 16,
      user_name: "Georgie Turner",
      first_name: "Georgie",
      last_name: "Turner",
      email: "Georgie.turner@gmail.com",
      password: "",
      bio: "Georgie, residing in Southwark, committed to making a positive change through volunteering.",
      current_number_of_opportunities: 0,
      total_opportunities: 10,
    },
    {
      id: 17,
      user_name: "Oliver Baker",
      first_name: "Oliver",
      last_name: "Baker",
      email: "oliver.baker@gmail.com",
      password: "",
      bio: "Oliver, from Greenwich, excited to lend a helping hand for community welfare.",
      current_number_of_opportunities: 2,
      total_opportunities: 14,
    },
    {
      id: 18,
      user_name: "Ava Mitchell",
      first_name: "Ava",
      last_name: "Mitchell",
      email: "ava.mitchell@gmail.com",
      password: "",
      bio: "Ava, a resident of Lambeth, passionate about contributing to social causes.",
      current_number_of_opportunities: 1,
      total_opportunities: 12,
    },
    {
      id: 19,
      user_name: "Henry Turner",
      first_name: "Henry",
      last_name: "Turner",
      email: "henry.turner@gmail.com",
      password: "",
      bio: "Henry, a resident of Merton, dedicated to volunteering for the betterment of the community.",
      current_number_of_opportunities: 3,
      total_opportunities: 16,
    },
    {
      id: 20,
      user_name: "Grace Williams",
      first_name: "Grace",
      last_name: "Williams",
      email: "grace.williams@gmail.com",
      password: "",
      bio: "Grace, living in Hackney, eager to contribute time and effort for community service.",
      current_number_of_opportunities: 1,
      total_opportunities: 9,
    },
    {
      id: 21,
      user_name: "Charlie Martin",
      first_name: "Charlie",
      last_name: "Martin",
      email: "charlie.martin@gmail.com",
      password: "",
      bio: "Charlie, a resident of Camden, enthusiastic about volunteering for a positive impact.",
      current_number_of_opportunities: 2,
      total_opportunities: 13,
    },
  ]);
};
